### ISSUE TITLE
error in generateUniqueId

### ISSUE THREAD

**Issue by segun-flexible** [seyi-js/vtpass-node#1] opened 2022-05-19 11:13 UTC
its giving error
response_description: 'IMPROPER REQUEST ID: NOT PROPER DATE FORMAT – FIRST 8 CHARACTERS MUST BE DATE (TODAY’S DATE – YYYYMMDD)',

**Comment by seyi-js** [comment] 2022-05-19 16:53
You can pass in the unique ID as into the methods( it seems vtpass has changed their method of generating ids, so i will have to make an update) till the issue is fixed. 
Thanks

**Comment by segun-flexible** [comment] 2022-05-20 14:16
make the update, they are now requiring  the Id to be YYYY-MM-DD GMT+1

**Comment by seyi-js** [comment] 2022-06-19 14:45
It has been resolved in the latest release.

**Closed as completed by seyi-js** 2022-06-19 14:45 UTC
